spring.application.name=smart-commerce

# MongoDB
spring.data.mongodb.uri=mongodb+srv://duneshvasa:Dunesh%401234@cluster0.dlm8ujk.mongodb.net/smart_commerce_db?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=smart_commerce_db

# Server
server.port=8080

# Logging
logging.level.com.smartcommerce=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# JWT
#jwt.secret=smartcommerce-super-secret-key-must-be-at-least-256-bits-long-for-hs256
#jwt.expiration=86400000
# 86400000ms = 24 hours

